import { NextRequest, NextResponse } from 'next/server';
import { octokit, getRepoParams, hasValidRepoParams } from '@/lib/github';
import { calculateRiskScore } from '@/lib/risk-score';
import { generateChecklist } from '@/lib/checklist';
import { getCollection } from '@/lib/db';
import { env } from '@/lib/env';

export async function POST(req: NextRequest) {
    try {
        const { pull_number } = await req.json();
        const repoParams = getRepoParams(req);
        if (!hasValidRepoParams(repoParams)) {
            return NextResponse.json(
                { error: 'Invalid repo format. Use owner/repo or configure GITHUB_REPO.' },
                { status: 400 }
            );
        }

        if (!pull_number) {
            return NextResponse.json({ error: 'pull_number is required' }, { status: 400 });
        }

        // 1. Fetch PR details
        const { data: pr } = await octokit.rest.pulls.get({
            ...repoParams,
            pull_number,
        });

        // 2. Fetch PR files
        const { data: files } = await octokit.rest.pulls.listFiles({
            ...repoParams,
            pull_number,
        });

        const filenames = files.map(f => f.filename);

        // 3. Analyze
        const risk = calculateRiskScore({
            changedFiles: pr.changed_files,
            additions: pr.additions,
            deletions: pr.deletions,
            filenames,
        });

        const checklist = generateChecklist({ filenames });

        // 4. Save to MongoDB
        const collection = await getCollection('pull_request_analyses');
        await collection.updateOne(
            { repo: `${repoParams.owner}/${repoParams.repo}`, number: pull_number },
            {
                $set: {
                    risk,
                    checklist,
                    updatedAt: new Date(),
                    title: pr.title,
                    url: pr.html_url
                }
            },
            { upsert: true }
        );

        // 5. Post/Update Comment (Idempotent)
        const commentBody = `
## 🩺 Repo Doctor Analysis
**Risk Score:** ${risk.score}/100 (${risk.level})
${risk.reasons.map(r => `- ${r}`).join('\n')}

### 📝 Checklist
${checklist}

*Generated by ${env.REPO_DOCTOR_BOT_NAME}*
    `.trim();

        // Find existing comment
        const { data: comments } = await octokit.rest.issues.listComments({
            ...repoParams,
            issue_number: pull_number,
        });

        const botComment = comments.find(c => c.body?.includes('Repo Doctor Analysis'));

        if (botComment) {
            await octokit.rest.issues.updateComment({
                ...repoParams,
                comment_id: botComment.id,
                body: commentBody,
            });
        } else {
            await octokit.rest.issues.createComment({
                ...repoParams,
                issue_number: pull_number,
                body: commentBody,
            });
        }

        return NextResponse.json({ success: true, risk, checklist });
    } catch (error: unknown) {
        console.error('PR Analysis Failed:', error);
        const message = error instanceof Error ? error.message : 'Unknown error';
        return NextResponse.json({ error: message }, { status: 500 });
    }
}
